# Generated by Django 5.0.7 on 2024-07-20 23:34

import cliente.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billetera',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carteracliente',
            name='cant_cuotas',
            field=models.DecimalField(decimal_places=5, max_digits=10, validators=[cliente.validators.validar_numeros_negativos]),
        ),
        migrations.AlterField(
            model_name='carteracliente',
            name='valor_cuota',
            field=models.DecimalField(decimal_places=5, max_digits=10, validators=[cliente.validators.validar_numeros_negativos]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='num_identificacion',
            field=models.CharField(max_length=20, validators=[cliente.validators.validar_solo_numeros]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, validators=[cliente.validators.validar_solo_numeros]),
        ),
    ]
