# Generated by Django 5.0.7 on 2024-07-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_billetera_importe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billetera',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
