# Generated by Django 5.0.7 on 2024-07-20 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FondoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_cuotas', models.IntegerField()),
                ('concepto', models.CharField(max_length=200)),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondos.fondo')),
            ],
        ),
        migrations.CreateModel(
            name='FondoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liquidez', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cartera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_cuotas', models.IntegerField()),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondos.fondo')),
            ],
        ),
        migrations.CreateModel(
            name='FondoLiquidez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=200)),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondos.fondo')),
            ],
        ),
    ]
