# Generated by Django 5.0.7 on 2024-07-20 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0003_alter_activo_nombre_alter_mercado_horario_and_more'),
        ('fondos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta', models.BooleanField()),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activo.activo')),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondos.fondo')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'COMPRA'), ('venta', 'VENTA')], max_length=6)),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondos.posicion')),
            ],
        ),
    ]
