# Generated by Django 5.0.7 on 2024-07-24 01:36

import fondos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0002_posicion_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondoliquidez',
            name='fecha',
            field=models.DateField(validators=[fondos.validators.validar_fecha_futura]),
        ),
        migrations.AlterField(
            model_name='fondoliquidez',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[fondos.validators.validar_cero]),
        ),
    ]
