# Generated by Django 5.0.7 on 2024-07-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0003_alter_activo_nombre_alter_mercado_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciohistorico',
            name='moneda',
        ),
        migrations.AddField(
            model_name='activo',
            name='moneda',
            field=models.CharField(choices=[('usd', 'DOLAR'), ('eur', 'EURO')], default='usd', max_length=3),
        ),
    ]
